### PR TITLE
Fix issue #7

### PR DESCRIPTION
**Pull request by jaredfolkins**
This is the finalized proposed fix for issue #7.

### CODE REVIEW

**Comment by cfreeman** [comment]
Just gave this a test in a project I'm upgrading to go1.6. Works as advertised, many thanks.

**Comment by fogleman** [comment]
@gordonklaus Can you please merge this?

**Comment by gordonklaus** [comment]
This is fixed in 21c960f

**Comment by fogleman** [comment]
@gordonklaus Thanks for the fix!

**Pull request closed without merging**
